name: Continuous integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install
      - name: Typecheck openapi-kit
        run: yarn workspace openapi-kit typecheck
      - name: Build openapi-kit
        run: yarn workspace openapi-kit build
      - name: Run openapi-kit in example
        run: yarn workspace example openapi
      - name: Ensure example works as expected
        run: yarn workspace example typecheck && yarn workspace example build
